// WAVE-B B1/B2 — the schema→RLS SQL generator. PURE (no network), so the "RLS is ALWAYS
// generated with tables" invariant (R2, spec §5 B2) is a deterministic, unit-tested property
// of the code, not a hope about model output. The agent never writes raw SQL: it passes a
// structured TableSpec[], and THIS module emits the DDL — every table gets:
//   • an `id uuid primary key default gen_random_uuid()`
//   • a `user_id uuid not null references auth.users(id) on delete cascade` owner column
//   • `alter table … enable row level security`
//   • four owner-scoped policies (select/insert/update/delete) keyed on `auth.uid() = user_id`
//
// There is no code path that creates a table without RLS. A malformed identifier throws
// (ProvisionError) rather than emitting unsafe DDL.

import { ProvisionError, type TableSpec, type ColumnSpec } from './types';

const IDENT = /^[a-z][a-z0-9_]{0,48}$/;
/** Reserved column names the generator owns — a spec may not redefine them. */
const RESERVED_COLUMNS = new Set(['id', 'user_id', 'created_at']);

const PG_TYPE: Record<ColumnSpec['type'], string> = {
  text: 'text',
  integer: 'integer',
  boolean: 'boolean',
  timestamptz: 'timestamptz',
  uuid: 'uuid',
  numeric: 'numeric',
  jsonb: 'jsonb',
};

const PG_DEFAULT: Record<NonNullable<ColumnSpec['default']>, string> = {
  now: 'now()',
  true: 'true',
  false: 'false',
  gen_random_uuid: 'gen_random_uuid()',
};

function assertIdent(name: string, kind: string): void {
  if (!IDENT.test(name)) {
    throw new ProvisionError(
      'bad_schema',
      `Ungültiger ${kind}-Name „${name}" — nur Kleinbuchstaben, Ziffern und _ (Start mit Buchstabe).`,
    );
  }
}

function columnDDL(col: ColumnSpec): string {
  assertIdent(col.name, 'Spalten');
  if (RESERVED_COLUMNS.has(col.name)) {
    throw new ProvisionError('bad_schema', `Spalte „${col.name}" ist reserviert und wird automatisch angelegt.`);
  }
  const parts = [`  "${col.name}" ${PG_TYPE[col.type]}`];
  if (col.notNull) parts.push('not null');
  if (col.default) parts.push(`default ${PG_DEFAULT[col.default]}`);
  return parts.join(' ');
}

/** Emit the CREATE TABLE + RLS + owner policies for one table. RLS is NON-OPTIONAL. */
function tableDDL(spec: TableSpec): string {
  assertIdent(spec.name, 'Tabellen');
  if (!Array.isArray(spec.columns) || spec.columns.length === 0) {
    throw new ProvisionError('bad_schema', `Tabelle „${spec.name}" braucht mindestens eine Spalte.`);
  }
  const cols = spec.columns.map(columnDDL);
  const t = spec.name;
  return [
    `create table if not exists public."${t}" (`,
    [
      '  id uuid primary key default gen_random_uuid()',
      // The owner column is the RLS anchor. auth.users is Supabase's auth schema; the
      // generated client sets user_id = auth.uid() on insert (B2 wiring).
      '  user_id uuid not null references auth.users(id) on delete cascade',
      ...cols,
      '  created_at timestamptz not null default now()',
    ].join(',\n'),
    ');',
    '',
    // RLS ALWAYS. No branch, no flag.
    `alter table public."${t}" enable row level security;`,
    '',
    // Four explicit owner-scoped policies. INSERT uses WITH CHECK so a user can only
    // insert rows they own; the rest use USING so a user can only see/mutate their own.
    `create policy "${t}_select_own" on public."${t}" for select using (auth.uid() = user_id);`,
    `create policy "${t}_insert_own" on public."${t}" for insert with check (auth.uid() = user_id);`,
    `create policy "${t}_update_own" on public."${t}" for update using (auth.uid() = user_id) with check (auth.uid() = user_id);`,
    `create policy "${t}_delete_own" on public."${t}" for delete using (auth.uid() = user_id);`,
  ].join('\n');
}

/**
 * Generate the full schema SQL for a set of tables. Guaranteed to enable RLS + owner
 * policies on every table. Throws ProvisionError on any invalid identifier/spec (never
 * emits unsafe DDL). The returned SQL is idempotent (IF NOT EXISTS + policy drops).
 */
export function generateSchemaSQL(tables: TableSpec[]): string {
  if (!Array.isArray(tables) || tables.length === 0) {
    throw new ProvisionError('bad_schema', 'Kein Schema angegeben — mindestens eine Tabelle nötig.');
  }
  if (tables.length > 20) {
    throw new ProvisionError('bad_schema', 'Zu viele Tabellen auf einmal (max 20).');
  }
  // Drop any pre-existing same-named policies first so re-running is idempotent (a second
  // provision of the same schema must not error on "policy already exists").
  const dropPolicies = tables
    .flatMap((t) => ['select', 'insert', 'update', 'delete'].map((op) => {
      assertIdent(t.name, 'Tabellen');
      return `drop policy if exists "${t.name}_${op}_own" on public."${t.name}";`;
    }))
    .join('\n');
  const bodies = tables.map(tableDDL).join('\n\n');
  return [
    '-- Generated by Goblin (WAVE-B). RLS enabled + owner-scoped on every table.',
    dropPolicies,
    '',
    bodies,
    '',
  ].join('\n');
}

/**
 * Structural assertion used by tests and defensively at apply time: every table named in
 * `tables` must have its RLS-enable line AND all four owner policies present in `sql`.
 * Returns the list of missing guarantees (empty = fully covered).
 */
export function auditRlsCoverage(tables: TableSpec[], sql: string): string[] {
  const missing: string[] = [];
  for (const t of tables) {
    if (!sql.includes(`alter table public."${t.name}" enable row level security;`)) {
      missing.push(`${t.name}: RLS not enabled`);
    }
    for (const op of ['select', 'insert', 'update', 'delete']) {
      if (!sql.includes(`"${t.name}_${op}_own"`)) missing.push(`${t.name}: missing ${op} policy`);
    }
  }
  return missing;
}
