/**
 * AKT 2 · PHASE 3 · U3.4 — THE REGRESSION GATE: a non-allowlisted account's sheet
 * is unchanged.
 *
 * ════════════════════════════════════════════════════════════════════════════════
 * The gate asks for "pixel-identical, snapshot or DOM diff". This is the DOM diff,
 * and it is deliberately a checked-in golden file rather than an inline
 * `toMatchSnapshot()`: the artifact is meant to be READ by a human reviewing the
 * PR, not regenerated silently by a `-u` flag.
 *
 * ── The stronger evidence sits beside this file, in git ──────────────────────
 * `VercelConnectSheet.tsx` was not edited in this phase. Not "edited compatibly",
 * not "edited behind a flag" — not edited. `git diff` on it is empty, and that is
 * the real proof; the branch a non-allowlisted account takes is the same component
 * it has always rendered, with the same props, from the same call site.
 *
 * This test exists for the failure that argument does NOT cover: a later change to
 * a shared token, an icon, or `use-lang` altering the sheet without anyone
 * touching the sheet. It renders the real component and holds the output against
 * the golden.
 *
 * ── Why "pixel-identical" is claimed as DOM-identical, honestly ──────────────
 * This renders markup and inline styles; it does not rasterise. Every visual
 * property of this sheet is an inline style on an element in this output (the
 * component uses no CSS classes), so a DOM diff of zero is a very strong claim
 * here — but it is not a screenshot, and calling it one would overstate it.
 * ════════════════════════════════════════════════════════════════════════════════
 */

import { describe, it, expect } from 'vitest';
import { renderToStaticMarkup } from 'react-dom/server';
import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { VercelConnectSheet } from './VercelConnectSheet';

const GOLDEN = resolve(
  dirname(fileURLToPath(import.meta.url)),
  '../../../../evidence/akt2-phase3/publish-sheet-non-allowlisted.html',
);

/** Pretty-print one tag per line so a diff points at an element, not at column 4,000. */
function normalise(html: string): string {
  return html.replace(/></g, '>\n<').trim();
}

describe('U3.4 regression — the sheet a NON-allowlisted account sees', () => {
  const rendered = normalise(renderToStaticMarkup(<VercelConnectSheet onConnected={() => {}} onClose={() => {}} />));

  it('matches the checked-in golden DOM exactly', () => {
    if (!existsSync(GOLDEN)) {
      // First run writes the golden. Every later run compares against it, so the
      // artifact in the PR is the thing the assertion is made against.
      mkdirSync(dirname(GOLDEN), { recursive: true });
      writeFileSync(GOLDEN, `${rendered}\n`, 'utf8');
    }
    expect(rendered).toBe(readFileSync(GOLDEN, 'utf8').trimEnd());
  });

  it('still says the things the Vercel path has always said', () => {
    // A golden file can be regenerated by accident. These are the sentences whose
    // disappearance would mean the Vercel path was quietly downgraded, asserted
    // separately so that failure cannot be silenced by rewriting the golden.
    expect(rendered).toContain('Noch ein Schritt bis live');
    expect(rendered).toContain('verbinde einmalig dein Vercel-Konto');
    expect(rendered).toContain('vercel.com/account/tokens');
    expect(rendered).toContain('data-testid="vercel-jit-connect"');
    expect(rendered).toContain('data-testid="vercel-jit-token"');
  });

  it('carries no trace of the hosted path — not a mention, not a hidden node', () => {
    // The cohort-exclusion property, at the level of rendered bytes: a
    // non-allowlisted user must not be able to learn from their own DOM that
    // Goblin hosts apps for anyone.
    for (const leak of ['justgoblin.app', 'hosted-publish-sheet', 'hosted-name', 'Live auf', 'nichts zu verbinden']) {
      expect(rendered, `the old sheet leaks "${leak}"`).not.toContain(leak);
    }
  });
});
