#!/usr/bin/env node
/**
 * fetch-fonts.mjs — vendor the design system's three families into the repo.
 *
 * The social renderer must not depend on a network fetch at render time, so the
 * fonts live here as files. This script is the auditable record of where they
 * came from: run it again and you get the same manifest, or a diff you can see.
 *
 * Coverage is deliberately NOT narrowed. Every unicode-range subset Google
 * serves for a requested weight is downloaded and its @font-face rule is kept
 * verbatim (only the `src` is repointed at the local file). German umlauts
 * (ä ö ü ß) and typographic quotes („ ‚ “ ”) must render, and the surest way to
 * guarantee that is to subset away nothing at all.
 *
 * All three families are SIL Open Font License 1.1. OFL.txt ships beside them.
 *
 *   node content/social/fonts/fetch-fonts.mjs
 */
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));

// A desktop Chrome UA is required: the css2 endpoint serves woff2 only to
// user agents it believes support it, and older formats to everything else.
const UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const FAMILIES = [
  { family: 'Manrope',          slug: 'manrope',          query: 'Manrope:wght@400;500;600;700;800', ofl: 'manrope' },
  // Instrument Serif is the ITALIC ACCENT ONLY. Shipping just the italic makes
  // that rule physical rather than a convention someone can forget.
  { family: 'Instrument Serif', slug: 'instrument-serif', query: 'Instrument+Serif:ital@1',          ofl: 'instrumentserif' },
  { family: 'JetBrains Mono',   slug: 'jetbrains-mono',   query: 'JetBrains+Mono:wght@400;500',      ofl: 'jetbrainsmono' },
];

async function get(url, accept) {
  const res = await fetch(url, { headers: { 'User-Agent': UA, ...(accept ? { Accept: accept } : {}) } });
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`);
  return res;
}

/** Split a Google Fonts css2 payload into blocks, keeping the subset comment. */
function parseFaces(css) {
  const faces = [];
  const re = /(?:\/\*\s*([^*]+?)\s*\*\/\s*)?@font-face\s*\{([^}]*)\}/g;
  let m;
  while ((m = re.exec(css))) {
    const subset = (m[1] ?? 'default').trim();
    const body = m[2];
    const pick = (k) => (new RegExp(`${k}:\\s*([^;]+);`).exec(body)?.[1] ?? '').trim();
    const url = /src:\s*url\((https:[^)]+)\)/.exec(body)?.[1];
    if (!url) continue;
    faces.push({
      subset,
      style: pick('font-style') || 'normal',
      weight: pick('font-weight') || '400',
      unicodeRange: pick('unicode-range'),
      url,
    });
  }
  return faces;
}

const manifest = [];
const cssOut = [
  '/* content/social/fonts/fonts.css — GENERATED by fetch-fonts.mjs, do not hand-edit.',
  ' *',
  ' * Self-hosted so the renderer never touches the network. Every unicode-range',
  ' * subset Google serves is present: nothing was subset away, so German umlauts',
  ' * and typographic quotes render from the real face, not a fallback.',
  ' *',
  ' * Manrope · Instrument Serif · JetBrains Mono — all SIL OFL 1.1, see OFL-*.txt.',
  ' *',
  " * font-display is 'block', not 'swap': a swap would let a screenshot capture",
  ' * the fallback face. The renderer additionally waits on document.fonts.ready',
  ' * and asserts document.fonts.check() before it shoots.',
  ' */',
  '',
];

for (const f of FAMILIES) {
  const url = `https://fonts.googleapis.com/css2?family=${f.query}&display=block`;
  const css = await (await get(url)).text();
  const faces = parseFaces(css);
  if (!faces.length) throw new Error(`no @font-face parsed for ${f.family}`);

  cssOut.push(`/* ── ${f.family} — ${faces.length} face(s), from ${url} ── */`);
  // Manrope and JetBrains Mono are VARIABLE fonts: Google returns the same file
  // for every weight you ask for, differing only in the declared font-weight.
  // Writing one file per (weight × subset) would have vendored 24 byte-identical
  // duplicates. Deduplicate on content hash and let the weights share a file.
  const byHash = new Map();
  for (const face of faces) {
    const bytes = Buffer.from(await (await get(face.url)).arrayBuffer());
    const sha256 = crypto.createHash('sha256').update(bytes).digest('hex');
    let file = byHash.get(sha256);
    if (!file) {
      file = `${f.slug}-${face.style}-${face.subset.replace(/[^a-z0-9]+/gi, '-').toLowerCase()}.woff2`;
      fs.writeFileSync(path.join(HERE, file), bytes);
      byHash.set(sha256, file);
    }
    manifest.push({
      family: f.family, file, subset: face.subset, style: face.style, weight: face.weight,
      bytes: bytes.length, sha256, source: face.url,
    });
    cssOut.push(
      '@font-face {',
      `  font-family: '${f.family}';`,
      `  font-style: ${face.style};`,
      `  font-weight: ${face.weight};`,
      '  font-display: block;',
      `  src: url('./${file}') format('woff2');`,
      ...(face.unicodeRange ? [`  unicode-range: ${face.unicodeRange};`] : []),
      '}',
    );
  }
  cssOut.push('');

  const ofl = await (await get(`https://raw.githubusercontent.com/google/fonts/main/ofl/${f.ofl}/OFL.txt`)).text();
  fs.writeFileSync(path.join(HERE, `OFL-${f.slug}.txt`), ofl);
}

fs.writeFileSync(path.join(HERE, 'fonts.css'), cssOut.join('\n'));
fs.writeFileSync(path.join(HERE, 'fonts.manifest.json'), JSON.stringify(manifest, null, 2) + '\n');

const files = new Map(manifest.map((m) => [m.file, m.bytes]));
const total = [...files.values()].reduce((a, b) => a + b, 0);
console.log(`${manifest.length} @font-face rules over ${files.size} woff2 files, ${(total / 1024).toFixed(1)} KB on disk`);
for (const fam of FAMILIES) {
  const rows = manifest.filter((m) => m.family === fam.family);
  const uniq = new Set(rows.map((m) => m.file));
  console.log(`  ${fam.family}: ${rows.length} rule(s) → ${uniq.size} file(s)`);
}
