/**
 * FOUNDER-WALK-5 · U1 — the verified fate of a chat turn.
 *
 * ── The claim that was not true ──────────────────────────────────────────────
 *
 * `chat-recovery.ts` told the founder "Sie läuft auf dem Server zu Ende — öffne diesen Chat
 * gleich nochmal, dann steht sie da." It reached that sentence by INFERENCE: the user row was
 * in the transcript, no assistant row followed it, therefore the turn must still be running.
 *
 * Absence of an answer is not evidence of a running turn. It is equally the signature of a
 * turn the 120s `CHAT_MAX_RUNTIME_MS` guard aborted — and that turn persists NOTHING
 * (chat-sessions.ts: the `break` on `signal.aborted` skips the `done` branch, which is the
 * only place an assistant row is written). Both states look identical from the transcript,
 * and the copy picked the flattering one. The founder waited for an answer that had already
 * been thrown away.
 *
 * ── What this registry is ────────────────────────────────────────────────────
 *
 * The one place that KNOWS. Every turn that starts registers here; every terminal path —
 * persisted, aborted by the runtime guard, failed upstream — writes its verdict here before
 * it returns. `GET /api/chat-sessions/:id/turn-status` reads it, so the client can ask
 * "what actually happened" instead of guessing from what is missing.
 *
 * ── Honest limitation, stated rather than hidden ─────────────────────────────
 *
 * This is PROCESS-LOCAL, exactly like `services/agent/run-registry.ts` (same deployment
 * assumption: apps/api/railway.json runs one long-lived `node dist/index.js`, so the process
 * outlives the request and "still running" is a real, checkable state). A restart or a second
 * replica loses the record — and then the endpoint answers `unknown`, NOT `running`. That is
 * the whole point: `unknown` is a state the copy is allowed to say out loud, and `running` is
 * one the client may only ever show when this registry confirmed it. Nothing infers upward.
 *
 * Making it durable would need a table (a migration this repo authors but does not apply),
 * so the honest degradation is the shipped behaviour, not a stopgap we pretend is complete.
 */

/** Why a turn ended. `max_runtime` is the guard that discards the answer. */
export type ChatTurnLostReason = 'max_runtime' | 'stream_failed' | 'persist_failed';

export type ChatTurnState =
  /** The turn is executing in THIS process right now. */
  | 'running'
  /** The answer was written to `standalone_messages`. It is in the transcript. */
  | 'completed'
  /** The turn ended without an answer. Nothing was saved; the work is gone. */
  | 'lost';

export interface ChatTurnRecord {
  turnId: string;
  sessionId: string;
  userId: string;
  state: ChatTurnState;
  reason: ChatTurnLostReason | null;
  startedAt: number;
  endedAt: number | null;
}

/**
 * How long a settled verdict stays readable. A founder who locks the phone mid-turn and
 * comes back over lunch must still find the truth, so this is generously longer than the
 * turn guard itself (120s) — but bounded, because the map is memory.
 */
export const TURN_RECORD_TTL_MS = 30 * 60 * 1000;

/** Bound the map so a pathological client cannot grow it without limit. */
const MAX_RECORDS = 2000;

const turns = new Map<string, ChatTurnRecord>();

function evictExpired(now: number): void {
  for (const [id, rec] of turns) {
    if (rec.endedAt !== null && now - rec.endedAt > TURN_RECORD_TTL_MS) turns.delete(id);
  }
  if (turns.size <= MAX_RECORDS) return;
  // Still over budget: drop the oldest SETTLED records first — a running turn's record is
  // the one thing we must never lose, because losing it would downgrade a live run to
  // `unknown` and cost the founder an answer that actually exists.
  const settled = [...turns.values()]
    .filter((r) => r.endedAt !== null)
    .sort((a, b) => (a.endedAt ?? 0) - (b.endedAt ?? 0));
  for (const rec of settled) {
    if (turns.size <= MAX_RECORDS) break;
    turns.delete(rec.turnId);
  }
}

/** Register a turn as running. `turnId` is generated by the caller (crypto.randomUUID). */
export function beginChatTurn(input: { turnId: string; sessionId: string; userId: string; now?: number }): void {
  const now = input.now ?? Date.now();
  evictExpired(now);
  turns.set(input.turnId, {
    turnId: input.turnId,
    sessionId: input.sessionId,
    userId: input.userId,
    state: 'running',
    reason: null,
    startedAt: now,
    endedAt: null,
  });
}

/**
 * Settle a turn. Idempotent and monotonic: the FIRST verdict wins, so a late
 * teardown path can never rewrite a `completed` turn into a `lost` one (the
 * finally-block abort runs after a successful persist on every normal turn).
 */
export function settleChatTurn(
  turnId: string,
  state: Exclude<ChatTurnState, 'running'>,
  reason: ChatTurnLostReason | null = null,
  now: number = Date.now(),
): void {
  const rec = turns.get(turnId);
  if (!rec || rec.state !== 'running') return;
  rec.state = state;
  rec.reason = reason;
  rec.endedAt = now;
}

/**
 * The most recent turn this process knows about for a session, ownership-checked.
 * `null` means "this process has no record" — which the caller must report as
 * `unknown`, never as a guess in either direction.
 */
export function latestChatTurn(sessionId: string, userId: string, now: number = Date.now()): ChatTurnRecord | null {
  evictExpired(now);
  let best: ChatTurnRecord | null = null;
  for (const rec of turns.values()) {
    if (rec.sessionId !== sessionId || rec.userId !== userId) continue;
    if (!best || rec.startedAt > best.startedAt) best = rec;
  }
  return best;
}

/** Test seam — clear the process-level turn map between unit tests. */
export function __resetChatTurnRegistry(): void {
  turns.clear();
}
