import { Octokit } from '@octokit/rest';
import { createClient } from '@supabase/supabase-js';
import { encryptData, decryptData } from './encryption';

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

export async function getDecryptedAccessToken(userId: string): Promise<string | null> {
  const { data, error } = await supabase
    .from('users')
    .select('github_access_token_encrypted')
    .eq('id', userId)
    .single();

  if (error || !data?.github_access_token_encrypted) {
    return null;
  }

  return decryptData(data.github_access_token_encrypted);
}

export async function createRepo(accessToken: string, options: { name: string; description?: string; private?: boolean }) {
  const octokit = new Octokit({ auth: accessToken });
  
  const { data } = await octokit.repos.createForAuthenticatedUser({
    name: options.name,
    description: options.description,
    private: options.private ?? true,
    auto_init: true
  });

  return data;
}

export async function pushFiles(accessToken: string, owner: string, repo: string, files: Record<string, string>) {
  const octokit = new Octokit({ auth: accessToken });

  // Get default branch ref
  let ref;
  try {
    ref = await octokit.git.getRef({ owner, repo, ref: 'heads/main' });
  } catch {
    ref = await octokit.git.getRef({ owner, repo, ref: 'heads/master' });
  }

  const currentCommitSha = ref.data.object.sha;

  // Get current tree
  const baseTree = await octokit.git.getCommit({ owner, repo, commit_sha: currentCommitSha });

  // Create blobs for all files
  const treeItems = [];
  for (const [path, content] of Object.entries(files)) {
    const { data: blob } = await octokit.git.createBlob({
      owner,
      repo,
      content: Buffer.from(content).toString('base64'),
      encoding: 'base64'
    });

    treeItems.push({
      path,
      mode: '100644' as const,
      type: 'blob' as const,
      sha: blob.sha
    });
  }

  // Create new tree
  const { data: newTree } = await octokit.git.createTree({
    owner,
    repo,
    base_tree: baseTree.data.tree.sha,
    tree: treeItems
  });

  // Create commit
  const { data: newCommit } = await octokit.git.createCommit({
    owner,
    repo,
    message: 'Initial commit — generated by Goblin 🔨',
    parents: [currentCommitSha],
    tree: newTree.sha
  });

  // Update ref
  await octokit.git.updateRef({
    owner,
    repo,
    ref: ref.data.ref.replace('refs/', ''),
    sha: newCommit.sha
  });
}

export async function disconnectGitHub(userId: string): Promise<void> {
  await supabase
    .from('users')
    .update({
      github_username: null,
      github_access_token_encrypted: null,
      github_connected_at: null
    })
    .eq('id', userId);
}

export async function saveGitHubConnection(userId: string, accessToken: string, username: string): Promise<void> {
  const encryptedToken = encryptData(accessToken);

  await supabase
    .from('users')
    .update({
      github_username: username,
      github_access_token_encrypted: encryptedToken,
      github_connected_at: new Date().toISOString()
    })
    .eq('id', userId);
}