// Auto-generated by: supabase gen types typescript --linked
// Regenerate when schema changes: pnpm --filter @goblin/api supabase gen types typescript --linked > packages/shared/src/database.types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string
          plan: 'seed' | 'craft' | 'forge'
          stripe_customer_id: string | null
          monthly_requests_used: number
          billing_cycle_start: string | null
          github_username: string | null
          github_access_token_encrypted: string | null
          created_at: string
        }
        Insert: {
          id: string
          email: string
          plan?: 'seed' | 'craft' | 'forge'
          stripe_customer_id?: string | null
          monthly_requests_used?: number
          billing_cycle_start?: string | null
          github_username?: string | null
          github_access_token_encrypted?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          email?: string
          plan?: 'seed' | 'craft' | 'forge'
          stripe_customer_id?: string | null
          monthly_requests_used?: number
          billing_cycle_start?: string | null
          github_username?: string | null
          github_access_token_encrypted?: string | null
          created_at?: string
        }
      }
      projects: {
        Row: {
          id: string
          user_id: string
          name: string
          description: string | null
          color: string | null
          github_repo: string | null
          model_preferences: Json | null
          storage_path: string | null
          last_active: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          name: string
          description?: string | null
          color?: string | null
          github_repo?: string | null
          model_preferences?: Json | null
          storage_path?: string | null
          last_active?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          name?: string
          description?: string | null
          color?: string | null
          github_repo?: string | null
          model_preferences?: Json | null
          storage_path?: string | null
          last_active?: string | null
          created_at?: string
        }
      }
      models: {
        Row: {
          id: string
          name: string
          slug: string
          provider: string
          layer: 'goblin_hosted' | 'free_api' | 'byok'
          description: string | null
          tags: string[] | null
          requires_key: boolean
          available: boolean
          phase: number
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          slug: string
          provider: string
          layer: 'goblin_hosted' | 'free_api' | 'byok'
          description?: string | null
          tags?: string[] | null
          requires_key?: boolean
          available?: boolean
          phase?: number
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          slug?: string
          provider?: string
          layer?: 'goblin_hosted' | 'free_api' | 'byok'
          description?: string | null
          tags?: string[] | null
          requires_key?: boolean
          available?: boolean
          phase?: number
          created_at?: string
        }
      }
      byok_keys: {
        Row: {
          id: string
          user_id: string
          provider: string
          key_encrypted: string
          key_hint: string | null
          validated_at: string | null
          revoked_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          provider: string
          key_encrypted: string
          key_hint?: string | null
          validated_at?: string | null
          revoked_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          provider?: string
          key_encrypted?: string
          key_hint?: string | null
          validated_at?: string | null
          revoked_at?: string | null
          created_at?: string
        }
      }
      chat_messages: {
        Row: {
          id: string
          project_id: string
          role: 'user' | 'assistant' | 'system'
          content: string
          model_used: string | null
          source_tier: 'goblin_hosted' | 'free_api' | 'byok' | null
          has_sendtocode: boolean
          created_at: string
        }
        Insert: {
          id?: string
          project_id: string
          role: 'user' | 'assistant' | 'system'
          content: string
          model_used?: string | null
          source_tier?: 'goblin_hosted' | 'free_api' | 'byok' | null
          has_sendtocode?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          project_id?: string
          role?: 'user' | 'assistant' | 'system'
          content?: string
          model_used?: string | null
          source_tier?: 'goblin_hosted' | 'free_api' | 'byok' | null
          has_sendtocode?: boolean
          created_at?: string
        }
      }
      code_injections: {
        Row: {
          id: string
          message_id: string | null
          project_id: string
          user_id: string
          payload: string
          payload_type: 'code' | 'prompt' | 'mixed'
          filename_hint: string | null
          applied_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          message_id?: string | null
          project_id: string
          user_id: string
          payload: string
          payload_type: 'code' | 'prompt' | 'mixed'
          filename_hint?: string | null
          applied_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          message_id?: string | null
          project_id?: string
          user_id?: string
          payload?: string
          payload_type?: 'code' | 'prompt' | 'mixed'
          filename_hint?: string | null
          applied_at?: string | null
          created_at?: string
        }
      }
      agent_runs: {
        Row: {
          id: string
          user_id: string
          project_id: string | null
          run_type: 'chat' | 'generate_project' | 'edit_file' | 'deploy' | 'code_injection'
          model_used: string | null
          source_tier: 'goblin_hosted' | 'free_api' | 'byok' | null
          input_tokens: number | null
          output_tokens: number | null
          cost_usd_internal: number | null
          status: 'pending' | 'running' | 'success' | 'failed'
          created_at: string
          completed_at: string | null
        }
        Insert: {
          id?: string
          user_id: string
          project_id?: string | null
          run_type: 'chat' | 'generate_project' | 'edit_file' | 'deploy' | 'code_injection'
          model_used?: string | null
          source_tier?: 'goblin_hosted' | 'free_api' | 'byok' | null
          input_tokens?: number | null
          output_tokens?: number | null
          cost_usd_internal?: number | null
          status?: 'pending' | 'running' | 'success' | 'failed'
          created_at?: string
          completed_at?: string | null
        }
        Update: {
          id?: string
          user_id?: string
          project_id?: string | null
          run_type?: 'chat' | 'generate_project' | 'edit_file' | 'deploy' | 'code_injection'
          model_used?: string | null
          source_tier?: 'goblin_hosted' | 'free_api' | 'byok' | null
          input_tokens?: number | null
          output_tokens?: number | null
          cost_usd_internal?: number | null
          status?: 'pending' | 'running' | 'success' | 'failed'
          created_at?: string
          completed_at?: string | null
        }
      }
      push_subscriptions: {
        Row: {
          id: string
          user_id: string
          endpoint: string
          keys: Json
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          endpoint: string
          keys: Json
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          endpoint?: string
          keys?: Json
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}
