'use client';

/**
 * WAVE-ABOUT-MANIFESTO · U4 — /manifesto, the reading half.
 *
 * This route previously had NO locale binding at all — a server component with
 * every string hardcoded in English (see lib/copy/manifesto.ts for the full
 * account). It now reads the same public/pre-auth precedence as every other
 * public surface, so a visitor who pressed DE gets the same answer here as on
 * /login and /about.
 *
 * The six beliefs are numbered by a CSS counter (styles/landing.css §18b), not by
 * digits in the copy: the number a reader sees is then always the position of the
 * item actually rendered. "Six things we believe" over five items would be the
 * page contradicting its own first belief.
 */

import Link from 'next/link';
import { Button } from '@/components/landing/ui/Button';
import { MANIFESTO_COPY } from '@/lib/copy/manifesto';
import { RichText } from '@/lib/copy/rich-text';
import HtmlLangSync from '@/components/i18n/HtmlLangSync';
import { useProseLang } from '@/lib/copy/prose-locale';

export function ManifestoProse() {
  // Pinned to English until real German prose exists — see AboutProse and
  // lib/copy/prose-locale.ts. One value for both the copy and `<html lang>`.
  const lang = useProseLang();
  const c = MANIFESTO_COPY[lang];

  return (
    <article className="lp-prose">
      <HtmlLangSync lang={lang} />

      <div className="lp-prose-inner">
        <Link href="/" className="lp-prose-back">{c.back}</Link>

        <header className="lp-prose-head">
          <div className="eyebrow">
            <span className="tick" aria-hidden="true" />
            {c.eyebrow}
          </div>
          <h1 className="lp-prose-h1">{c.h1}</h1>
        </header>

        <div className="lp-beliefs" data-testid="manifesto-beliefs">
          {c.beliefs.map((belief) => (
            <section className="lp-belief" key={belief.title}>
              {/* The digit itself is generated by the counter — this element
                  carries only the rule and the accent colour. */}
              <div className="lp-belief-num" aria-hidden="true" />
              <h3 className="lp-belief-title">{belief.title}</h3>
              {belief.body.map((p, i) => (
                <p key={i}><RichText>{p}</RichText></p>
              ))}
            </section>
          ))}
        </div>

        <section className="lp-prose-close">
          <h2 className="lp-prose-h2">{c.soHead}</h2>
          {c.so.map((p, i) => (
            <p key={i}><RichText>{p}</RichText></p>
          ))}
          <p className="lp-prose-kicker">{c.soKicker}</p>

          <div className="lp-prose-cta">
            {/* /register is the signup route the landing's own CTAs point at
                (Hero, Nav, Outro) — same destination, so this page does not
                invent a second front door. */}
            <Button href="/register" variant="primary" size="large">
              {c.ctaLabel} <span className="arrow" aria-hidden="true">→</span>
            </Button>
            <div className="lp-prose-cta-sub">{c.ctaSubline}</div>
          </div>
        </section>
      </div>
    </article>
  );
}

export default ManifestoProse;
