import { chromium } from '@playwright/test';
import fs from 'node:fs'; import path from 'node:path';
const env=(k)=>{const t=fs.readFileSync('.env.local','utf8');const m=t.match(new RegExp('^'+k+'=(.*)$','m'));return m?m[1].trim():'';};
const EMAIL=env('TEST_ACCOUNT_EMAIL'),PW=env('TEST_ACCOUNT_PASSWORD'),SUPA=env('NEXT_PUBLIC_SUPABASE_URL'),ANON=env('NEXT_PUBLIC_SUPABASE_ANON_KEY');
const BASE='https://www.justgoblin.com';
const OUT=path.join('sprint-codetab','run-bigfix','shots','r2'); fs.mkdirSync(OUT,{recursive:true});
const b=await chromium.launch({headless:true});
const ctx=await b.newContext({viewport:{width:390,height:844,isMobile:true,hasTouch:true,deviceScaleFactor:2}});
const p=await ctx.newPage();
const res=await p.request.post(`${SUPA}/auth/v1/token?grant_type=password`,{headers:{'Content-Type':'application/json',apikey:ANON},data:{email:EMAIL,password:PW}});
const t=await res.json();
await p.goto(`${BASE}/auth/magic-callback#access_token=${t.access_token}&refresh_token=${t.refresh_token}&expires_in=3600&token_type=bearer&type=magiclink`,{waitUntil:'domcontentloaded'});
await p.waitForURL(/\/dashboard/,{timeout:30000}).catch(()=>{});
await p.waitForTimeout(6000); // full auth settle
await p.goto(`${BASE}/dashboard#profile`,{waitUntil:'domcontentloaded'});
await p.waitForTimeout(5000);
const emailVal=await p.evaluate(()=>{const el=document.querySelector('[data-testid="form-email"]');return el?el.innerText:'(no form-email el)';}).catch(e=>'ERR:'+e.message);
console.log('profile email field:', JSON.stringify(emailVal));
await p.screenshot({path:path.join(OUT,'profile-isolated.png')});
await b.close();
